### ISSUE TITLE
The Ability to Retain Data Once App is Terminated

### ISSUE THREAD

**Issue by seanjoo4** [aidanandrucyk/AntColonyMobileGame#5]
**Describe the bug**
Whenever the app closes, the app resets to default settings.

**Expected behavior**
The app should behave in a way so that users can continue their progress from their last played state.

**Severity of the bug**
5

**Screenshots**
n/a

**Additional context**
n/a

**Comment by aidanandrucyk** [comment]
saved preferences implemented
